import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: {
    // absolute:'', for child for complete ignore layout metadata
    default: "Franchoice World",
    template: "%s | Franchoice World",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mainBody">
        <main className="flex flex-col min-h-screen">
          <Header />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
