import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

export const metadata: Metadata = {
  title: {
    // absolute:'', for child for complete ignore layout metadata
    default: "Franchoice World",
    template: "%s | Franchoice World",
  },
  description: "Generated by create next app",
};

const footerItem = [
  {
    id: "11",
    title: "Company",
    child: [
      {
        id: 1,
        name: "About us",
        path: "/about",
      },
      {
        id: 2,
        name: "Services",
        path: "/services",
      },
      {
        id: 3,
        name: "Knowledge Center",
        path: "/knowledge_center",
      },
      {
        id: 4,
        name: "Contact Us",
        path: "/contact_us",
      },
    ],
  },
  {
    id: "22",
    title: "Support",
    child: [
      {
        name: "Help Center",
        path: "/help_center",
      },
      {
        name: "Terms of service",
        path: "/terms_of_service",
      },
      {
        name: "Legal",
        path: "/legal",
      },
      {
        name: "Privacy policy",
        path: "/privacy-policy",
      },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mainBody">
        <main className="flex flex-col min-h-screen">
          <Header />
          {children}
        </main>
        <Footer props={footerItem} />
      </body>
    </html>
  );
}
